using System;
using System.Xml.Serialization;

namespace Avaco.BigBlueButton.Api.Models.Response {

    /// <summary>
    /// This class models the response data from a create request, it contains details about the newly created meeting as well
    /// as the fields defined in the class BasicResponse
    /// </summary>
    /// <inheritdoc/>
    public class CreateResponse : BasicResponse {
        /// <summary>
        /// The meeting ID of the newly created meeting
        /// </summary>
        [XmlElement ("meetingId")]
        public string MeetingId { get; set; }

        /// <summary>
        /// The internal meeting ID of the newly created meeting (this one is generated by the server)
        /// </summary>
        [XmlElement ("internalMeetingId")]
        public string InternalMeetingId { get; set; }

        /// <summary>
        /// In case of an breakout room this field contains the meeting ID of the partent meeting
        /// </summary>
        [XmlElement ("parentMeetingId")]
        public string ParentMeetingId { get; set; }

        /// <summary>
        /// The attendee password (the one provided on creation or a randomly generated one)
        /// </summary>
        [XmlElement ("attendeePW")]
        public string AttendeePW { get; set; }

        /// <summary>
        /// The moderator password (the one provided on creation or a randomly generated one)
        /// </summary>
        [XmlElement ("moderatorPW")]
        public string ModeratorPW { get; set; }

        /// <summary>
        /// The creation timestamp of the meeting
        /// </summary>
        [XmlElement ("createTime")]
        public long CreateTime { get; set; }

        /// <summary>
        /// The voice bridge parameter provided on the creation call
        /// </summary>
        [XmlElement ("voiceBridge")]
        public string VoiceBridge { get; set; }

        /// <summary>
        /// The dial in phone number provided on the creation call
        /// </summary>
        [XmlElement ("dialNumber")]
        public string DialNumber { get; set; }

        /// <summary>
        /// The creation date of the meeting
        /// </summary>
        [XmlElement ("createDate")]
        public string CreateDate { get; set; }

        /// <summary>
        /// An indiactor if already a user has joined the meeting
        /// </summary>
        [XmlElement ("hasUserJoined")]
        public bool HasUserJoined { get; set; }

        /// <summary>
        /// The duration of the meeting
        /// </summary>
        [XmlElement ("duration")]
        public long Duration { get; set; }

        /// <summary>
        /// An indicator if the meeting was ended by a end call
        /// </summary>
        [XmlElement ("hasBeenForciblyEnded")]
        public bool HasBeenForciblyEnded { get; set; }
    }
}